FROM golang:1.24-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/cron ./cmd/cron

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /out/cron /app/cron
CMD ["/app/cron"]
